DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS TeacherLessons;
DROP TABLE IF EXISTS StudentLessons;
DROP TABLE IF EXISTS Schedules;
DROP TABLE IF EXISTS Lessons;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Students;
